spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: ${JWT_SECRET} # JWT 시크릿 키
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION}  # Access Token 만료 시간
      refresh-expiration-time: ${JWT_ACCESS_EXPIRATION}  #  Refresh Token 만료 시간