spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: ${JWT_SECRET} # JWT 시크릿 키
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION}  # Access Token 만료 시간
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION}  #  Refresh Token 만료 시간

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
oauth:
  google:
    client_id: ${OAUTH_GOOGLE_CLIENT_ID}
    google_secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect_uri: ${OAUTH_GOOGLE_REDIRECT_URI}
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}